version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-management-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=tasks
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - task-management-network

  db:
    image: mysql:8.0
    container_name: task-management-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - task-management-network

networks:
  task-management-network:
    driver: bridge

volumes:
  dbdata:
